### ISSUE TITLE
README contains incorrect usage examples

### ISSUE THREAD

**Issue by blockchain-art** [zoedsoupe/postgrest-ex#1]
The usage examples for this package appear to mistakenly be a copy / paste of this https://github.com/zoedsoupe/storage-ex

**Comment by zoedsoupe** [comment]
yeah, you're correct! sorry for the misunderstanding, i'll solve it very soon, or if you could and wanna open a PR it will ok too.

**Comment by zoedsoupe** [comment]
just fixed that! thank you for the report
